services:

  # Frontend con nginx
  # La API y Mongo se levantan desde el proyecto ApiIbermon
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ibermon_frontend
    restart: unless-stopped
    ports:
      - "25014:80"
    networks:
      - ibermon_network

networks:
  # Red ya creada por docker-compose de ApiIbermon
  ibermon_network:
    external: true
    name: ibermon-api_ibermon_network
